import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'hi' | 'te';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    'nav.destinations': 'Destinations',
    'nav.experiences': 'Experiences',
    'nav.plan': 'Plan Trip',
    'nav.signIn': 'Sign In',
    'nav.signOut': 'Sign Out',
    
    // Hero
    'hero.badge': 'Explore 1000+ Destinations',
    'hero.title1': 'Discover Your Next',
    'hero.title2': 'Adventure Awaits',
    'hero.subtitle': 'Embark on extraordinary journeys with AI-powered travel planning, personalized itineraries, and immersive experiences',
    'hero.startPlanning': 'Start Planning',
    'hero.exploreDestinations': 'Explore Destinations',
    'hero.destinations': 'Destinations',
    'hero.support': 'Support',
    
    // Trip Planner
    'planner.badge': 'AI-Powered Planning',
    'planner.title': 'Plan Your',
    'planner.titleHighlight': 'Perfect Trip',
    'planner.subtitle': 'Let our AI assistant create a personalized itinerary based on your preferences',
    'planner.viewHistory': 'View',
    'planner.hideHistory': 'Hide',
    'planner.bookingHistory': 'Booking History',
    'planner.yourBookingHistory': 'Your Booking History',
    'planner.destination': 'Destination',
    'planner.whereTo': 'Where to?',
    'planner.startDate': 'Start Date',
    'planner.endDate': 'End Date',
    'planner.travelers': 'Number of Travelers',
    'planner.traveler': 'Traveler',
    'planner.travelersPlural': 'Travelers',
    'planner.budget': 'Budget Range',
    'planner.selectBudget': 'Select budget',
    'planner.budgetLow': 'Budget (₹10k - ₹25k)',
    'planner.budgetModerate': 'Moderate (₹25k - ₹50k)',
    'planner.budgetLuxury': 'Luxury (₹50k - ₹1L)',
    'planner.budgetPremium': 'Premium (₹1L+)',
    'planner.interests': 'Your Interests',
    'planner.selectInterests': 'Select activities you enjoy',
    'planner.specialRequests': 'Special Requests',
    'planner.specialRequestsPlaceholder': 'Any specific requirements, dietary restrictions, accessibility needs...',
    'planner.createItinerary': 'Create My Itinerary',
    'planner.creating': 'Creating...',
    'planner.tripPlanned': 'Your Trip is Planned!',
    'planner.savedToHistory': 'Your trip has been saved to your booking history',
    'planner.signInToSave': 'Sign in to save your trips',
    'planner.travelDates': 'Travel Dates',
    'planner.to': 'to',
    'planner.person': 'Person',
    'planner.people': 'People',
    'planner.selectedInterests': 'Selected Interests',
    'planner.planAnotherTrip': 'Plan Another Trip',
    'planner.getDetailedItinerary': 'View Detailed Itinerary',
    'planner.hideItinerary': 'Hide Itinerary',
    
    // Itinerary
    'itinerary.title': 'Your Detailed Itinerary',
    'itinerary.day': 'Day',
    'itinerary.morning': 'Morning',
    'itinerary.afternoon': 'Afternoon',
    'itinerary.evening': 'Evening',
    'itinerary.tips': 'Travel Tips',
    'itinerary.tip1': 'Carry light cotton clothes for day tours',
    'itinerary.tip2': 'Keep local currency for small purchases',
    'itinerary.tip3': 'Stay hydrated and carry water bottle',
    'itinerary.tip4': 'Respect local customs and traditions',
    
    // Interests
    'interest.adventure': 'Adventure',
    'interest.beach': 'Beach',
    'interest.culture': 'Culture',
    'interest.wildlife': 'Wildlife',
    'interest.photography': 'Photography',
    'interest.food': 'Food',
    'interest.hiking': 'Hiking',
    'interest.relaxation': 'Relaxation',
    'interest.shopping': 'Shopping',
    'interest.history': 'History',
    
    // Destinations Section
    'destinations.badge': 'Popular Destinations',
    'destinations.title': 'Popular',
    'destinations.titleHighlight': 'Destinations',
    'destinations.subtitle': 'Handpicked destinations that promise unforgettable experiences',
    'destinations.bookNow': 'Book Now',
    'destinations.all': 'All',
    'destinations.trending': 'Trending',
    'destinations.startingFrom': 'Starting from',
    'destinations.reviews': 'reviews',
    'destinations.noResults': 'No destinations found in this category.',
    
    // Destination Names
    'dest.himalayanTrails': 'Himalayan Trails',
    'dest.himalayanTrails.location': 'Northern Mountains',
    'dest.himalayanTrails.desc': 'Experience breathtaking mountain vistas, serene monasteries, and adventure sports',
    'dest.coastalParadise': 'Coastal Paradise',
    'dest.coastalParadise.location': 'Southern Beaches',
    'dest.coastalParadise.desc': 'Crystal clear waters, golden sands, and vibrant marine life await',
    'dest.heritageWonders': 'Heritage Wonders',
    'dest.heritageWonders.location': 'Cultural Heartland',
    'dest.heritageWonders.desc': 'Explore ancient temples, royal palaces, and rich cultural traditions',
    'dest.wildlifeSafari': 'Wildlife Safari',
    'dest.wildlifeSafari.location': 'National Parks',
    'dest.wildlifeSafari.desc': 'Encounter majestic tigers, elephants, and rare wildlife in their natural habitat',
    'dest.teaGardens': 'Tea Gardens',
    'dest.teaGardens.location': 'Hill Stations',
    'dest.teaGardens.desc': 'Rolling tea plantations, misty hills, and colonial charm',
    'dest.desertAdventure': 'Desert Adventure',
    'dest.desertAdventure.location': 'Western Deserts',
    'dest.desertAdventure.desc': 'Experience camel safaris, sand dunes, and starlit desert nights',
    'dest.goaBeaches': 'Goa Beaches',
    'dest.goaBeaches.location': 'Goa',
    'dest.goaBeaches.desc': 'Famous beaches, nightlife, Portuguese architecture, and seafood',
    'dest.varanasiGhats': 'Varanasi Ghats',
    'dest.varanasiGhats.location': 'Uttar Pradesh',
    'dest.varanasiGhats.desc': 'Spiritual capital of India with ancient ghats and temples',
    'dest.kazirangaSafari': 'Kaziranga Safari',
    'dest.kazirangaSafari.location': 'Assam',
    'dest.kazirangaSafari.desc': 'Home to the one-horned rhinoceros and diverse wildlife',
    
    // Tags
    'tag.adventure': 'Adventure',
    'tag.nature': 'Nature',
    'tag.trekking': 'Trekking',
    'tag.beach': 'Beach',
    'tag.relaxation': 'Relaxation',
    'tag.waterSports': 'Water Sports',
    'tag.culture': 'Culture',
    'tag.history': 'History',
    'tag.architecture': 'Architecture',
    'tag.wildlife': 'Wildlife',
    'tag.photography': 'Photography',
    'tag.safari': 'Safari',
    'tag.peaceful': 'Peaceful',
    'tag.scenic': 'Scenic',
    'tag.unique': 'Unique',
    'tag.nightlife': 'Nightlife',
    'tag.food': 'Food',
    'tag.spiritual': 'Spiritual',
    'tag.heritage': 'Heritage',
    
    // Experiences Section
    'experiences.badge': 'Unique Experiences',
    'experiences.title': 'Unique',
    'experiences.titleHighlight': 'Experiences',
    'experiences.subtitle': 'Go beyond sightseeing with immersive activities designed for every type of traveler',
    'experiences.bookNow': 'Book Now',
    'experiences.all': 'All',
    'experiences.leisure': 'Leisure',
    'experiences.noResults': 'No experiences found in this category.',
    'experiences.selected': 'Experience Selected!',
    'experiences.addedMessage': 'has been added. Head to Trip Planner to complete your booking.',
    
    // Experience Names
    'exp.trekkingAdventures': 'Trekking Adventures',
    'exp.trekkingAdventures.desc': 'Conquer challenging trails with experienced guides through breathtaking landscapes',
    'exp.waterSports': 'Water Sports',
    'exp.waterSports.desc': 'Surfing, diving, and kayaking in pristine waters with certified instructors',
    'exp.photographyTours': 'Photography Tours',
    'exp.photographyTours.desc': 'Capture stunning landscapes with professional photographers as your guides',
    'exp.culinaryExperiences': 'Culinary Experiences',
    'exp.culinaryExperiences.desc': 'Taste authentic local cuisine and learn cooking secrets from master chefs',
    'exp.campingGlamping': 'Camping & Glamping',
    'exp.campingGlamping.desc': 'Sleep under the stars in luxury tents or traditional camping setups',
    'exp.culturalImmersion': 'Cultural Immersion',
    'exp.culturalImmersion.desc': 'Live with locals and learn traditional crafts, dance, and customs',
    'exp.cyclingTours': 'Cycling Tours',
    'exp.cyclingTours.desc': 'Explore scenic routes on two wheels with expert-guided cycling adventures',
    'exp.musicDance': 'Music & Dance',
    'exp.musicDance.desc': 'Experience traditional music performances and learn folk dance forms',
    
    // Duration & Difficulty
    'duration.3-7days': '3-7 days',
    'duration.halfToFull': 'Half day to Full day',
    'duration.1-5days': '1-5 days',
    'duration.2-4hours': '2-4 hours',
    'duration.1-3nights': '1-3 nights',
    'duration.2-7days': '2-7 days',
    'duration.2-3hours': '2-3 hours',
    'difficulty.moderateToHard': 'Moderate to Hard',
    'difficulty.easyToModerate': 'Easy to Moderate',
    'difficulty.easy': 'Easy',
    'difficulty.moderate': 'Moderate',
    
    // Features Section
    'features.badge': 'Why Choose VirtueYatra',
    'features.title': 'Why Choose',
    'features.titleHighlight': 'VirtueYatra',
    'features.subtitle': 'Experience travel planning reimagined with cutting-edge technology and personalized service',
    'features.aiAssistant': 'AI Travel Assistant',
    'features.aiAssistant.desc': 'Get personalized recommendations and instant answers to all your travel questions',
    'features.smartItinerary': 'Smart Itinerary Planning',
    'features.smartItinerary.desc': 'Create perfect travel plans with AI-optimized routes and schedules',
    'features.immersive': 'Immersive Experiences',
    'features.immersive.desc': 'Preview destinations with AR/VR technology before you visit',
    'features.safeSec': 'Safe & Secure',
    'features.safeSec.desc': 'Travel with confidence with our verified partners and secure booking',
    'features.globalCoverage': 'Global Coverage',
    'features.globalCoverage.desc': 'Explore destinations across continents with local insights',
    'features.personalized': 'Personalized Just for You',
    'features.personalized.desc': 'Tailored recommendations based on your preferences and travel style',
    
    // Footer
    'footer.tagline': 'Your intelligent travel companion for discovering extraordinary destinations and creating unforgettable memories.',
    'footer.company': 'Company',
    'footer.aboutUs': 'About Us',
    'footer.careers': 'Careers',
    'footer.press': 'Press',
    'footer.blog': 'Blog',
    'footer.support': 'Support',
    'footer.helpCenter': 'Help Center',
    'footer.safety': 'Safety',
    'footer.termsOfService': 'Terms of Service',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.discover': 'Discover',
    'footer.destinations': 'Destinations',
    'footer.experiences': 'Experiences',
    'footer.travelGuides': 'Travel Guides',
    'footer.giftCards': 'Gift Cards',
    'footer.rights': 'All rights reserved.',
    
    // Chatbot
    'chatbot.title': 'VirtueYatra Assistant',
    'chatbot.subtitle': 'Always here to help',
    'chatbot.greeting': "Hello! 👋 I'm your VirtueYatra travel assistant. How can I help you plan your perfect trip today?",
    'chatbot.placeholder': 'Ask me anything...',
    'chatbot.response.hello': "Hello! I'm excited to help you discover amazing destinations. What kind of experience are you looking for?",
    'chatbot.response.beach': "Our Coastal Paradise destinations are perfect for beach lovers! With crystal clear waters and golden sands, you'll find relaxation and adventure. The package starts from ₹18,499. Would you like to know more?",
    'chatbot.response.mountain': "The Himalayan Trails offer breathtaking mountain vistas and adventure sports! It's perfect for trekking and experiencing serene monasteries. Packages start from ₹25,999. Interested in booking?",
    'chatbot.response.budget': "We have options for every budget! Our packages range from ₹16,999 to ₹32,999. Budget travelers love our Tea Gardens package at ₹16,999, while adventure seekers enjoy the Wildlife Safari at ₹32,999. What's your budget range?",
    'chatbot.response.wildlife': "Our Wildlife Safari packages offer incredible encounters with majestic tigers, elephants, and rare wildlife in their natural habitat. Perfect for photographers! Starting at ₹32,999. Shall I help you plan this adventure?",
    'chatbot.response.book': "Great! To book your trip, I recommend using our Trip Planner below. Just fill in your details, and we'll create a personalized itinerary for you. You can also click 'Explore' on any destination card for quick booking!",
    'chatbot.response.culture': "Our Heritage Wonders tour takes you through ancient temples, royal palaces, and rich cultural traditions. It's rated 4.7 stars with over 3,000 reviews! Starting from ₹22,999. Would you like more details?",
    'chatbot.response.thank': "You're very welcome! If you need any more help planning your trip, I'm always here. Happy travels! 🌍✈️",
    'chatbot.response.default': "That's a great question! I can help you with destinations, pricing, booking information, and travel recommendations. Feel free to ask about beaches, mountains, wildlife, cultural experiences, or any specific travel needs!",
    
    // Toast messages
    'toast.missingInfo': 'Missing Information',
    'toast.fillDestinationDates': 'Please fill in destination and dates.',
    'toast.errorSavingTrip': 'Error saving trip',
    'toast.tripCreated': 'Trip Plan Created!',
    'toast.tripSaved': 'Your trip to {destination} has been saved!',
    'toast.tripReadySignIn': 'Your itinerary for {destination} is ready! Sign in to save your trips.',
    'toast.tripDeleted': 'Trip deleted',
    'toast.tripDeletedDesc': 'Your trip has been removed from history.',
    
    // Virtual World
    'virtualWorld.button': 'View Virtual World',
    'virtualWorld.title': '360° Virtual Tours',
    'virtualWorld.clickToExplore': 'Click to start the 360° experience',
    'virtualWorld.selectDestination': 'Select Destination',
    'virtualWorld.tip': '💡 Tip: Drag to look around in 360°. Use mouse wheel to zoom.',
  },
  hi: {
    // Header
    'nav.destinations': 'गंतव्य',
    'nav.experiences': 'अनुभव',
    'nav.plan': 'यात्रा योजना',
    'nav.signIn': 'साइन इन',
    'nav.signOut': 'साइन आउट',
    
    // Hero
    'hero.badge': '1000+ गंतव्य खोजें',
    'hero.title1': 'अपना अगला खोजें',
    'hero.title2': 'साहसिक इंतजार कर रहा है',
    'hero.subtitle': 'AI-संचालित यात्रा योजना, व्यक्तिगत यात्रा कार्यक्रम और इमर्सिव अनुभवों के साथ असाधारण यात्राओं पर निकलें',
    'hero.startPlanning': 'योजना शुरू करें',
    'hero.exploreDestinations': 'गंतव्य खोजें',
    'hero.destinations': 'गंतव्य',
    'hero.support': 'सहायता',
    
    // Trip Planner
    'planner.badge': 'AI-संचालित योजना',
    'planner.title': 'अपनी योजना बनाएं',
    'planner.titleHighlight': 'सही यात्रा',
    'planner.subtitle': 'हमारा AI सहायक आपकी प्राथमिकताओं के आधार पर व्यक्तिगत यात्रा कार्यक्रम बनाए',
    'planner.viewHistory': 'देखें',
    'planner.hideHistory': 'छिपाएं',
    'planner.bookingHistory': 'बुकिंग इतिहास',
    'planner.yourBookingHistory': 'आपका बुकिंग इतिहास',
    'planner.destination': 'गंतव्य',
    'planner.whereTo': 'कहाँ जाना है?',
    'planner.startDate': 'आरंभ तिथि',
    'planner.endDate': 'समाप्ति तिथि',
    'planner.travelers': 'यात्रियों की संख्या',
    'planner.traveler': 'यात्री',
    'planner.travelersPlural': 'यात्री',
    'planner.budget': 'बजट सीमा',
    'planner.selectBudget': 'बजट चुनें',
    'planner.budgetLow': 'बजट (₹10k - ₹25k)',
    'planner.budgetModerate': 'मध्यम (₹25k - ₹50k)',
    'planner.budgetLuxury': 'लक्जरी (₹50k - ₹1L)',
    'planner.budgetPremium': 'प्रीमियम (₹1L+)',
    'planner.interests': 'आपकी रुचियां',
    'planner.selectInterests': 'अपनी पसंदीदा गतिविधियां चुनें',
    'planner.specialRequests': 'विशेष अनुरोध',
    'planner.specialRequestsPlaceholder': 'कोई विशिष्ट आवश्यकताएं, आहार प्रतिबंध, पहुंच संबंधी आवश्यकताएं...',
    'planner.createItinerary': 'मेरा यात्रा कार्यक्रम बनाएं',
    'planner.creating': 'बना रहे हैं...',
    'planner.tripPlanned': 'आपकी यात्रा की योजना बन गई!',
    'planner.savedToHistory': 'आपकी यात्रा आपके बुकिंग इतिहास में सहेज ली गई है',
    'planner.signInToSave': 'अपनी यात्राएं सहेजने के लिए साइन इन करें',
    'planner.travelDates': 'यात्रा तिथियां',
    'planner.to': 'से',
    'planner.person': 'व्यक्ति',
    'planner.people': 'लोग',
    'planner.selectedInterests': 'चयनित रुचियां',
    'planner.planAnotherTrip': 'एक और यात्रा की योजना बनाएं',
    'planner.getDetailedItinerary': 'विस्तृत यात्रा कार्यक्रम देखें',
    'planner.hideItinerary': 'यात्रा कार्यक्रम छिपाएं',
    
    // Itinerary
    'itinerary.title': 'आपका विस्तृत यात्रा कार्यक्रम',
    'itinerary.day': 'दिन',
    'itinerary.morning': 'सुबह',
    'itinerary.afternoon': 'दोपहर',
    'itinerary.evening': 'शाम',
    'itinerary.tips': 'यात्रा सुझाव',
    'itinerary.tip1': 'दिन के दौरे के लिए हल्के सूती कपड़े ले जाएं',
    'itinerary.tip2': 'छोटी खरीदारी के लिए स्थानीय मुद्रा रखें',
    'itinerary.tip3': 'हाइड्रेटेड रहें और पानी की बोतल साथ रखें',
    'itinerary.tip4': 'स्थानीय रीति-रिवाजों और परंपराओं का सम्मान करें',
    
    // Interests
    'interest.adventure': 'साहसिक',
    'interest.beach': 'समुद्र तट',
    'interest.culture': 'संस्कृति',
    'interest.wildlife': 'वन्यजीव',
    'interest.photography': 'फोटोग्राफी',
    'interest.food': 'भोजन',
    'interest.hiking': 'पैदल यात्रा',
    'interest.relaxation': 'विश्राम',
    'interest.shopping': 'खरीदारी',
    'interest.history': 'इतिहास',
    
    // Destinations Section
    'destinations.badge': 'लोकप्रिय गंतव्य',
    'destinations.title': 'लोकप्रिय',
    'destinations.titleHighlight': 'गंतव्य',
    'destinations.subtitle': 'हाथ से चुने गए गंतव्य जो अविस्मरणीय अनुभवों का वादा करते हैं',
    'destinations.bookNow': 'अभी बुक करें',
    'destinations.all': 'सभी',
    'destinations.trending': 'ट्रेंडिंग',
    'destinations.startingFrom': 'शुरू से',
    'destinations.reviews': 'समीक्षाएं',
    'destinations.noResults': 'इस श्रेणी में कोई गंतव्य नहीं मिला।',
    
    // Destination Names
    'dest.himalayanTrails': 'हिमालयन ट्रेल्स',
    'dest.himalayanTrails.location': 'उत्तरी पर्वत',
    'dest.himalayanTrails.desc': 'लुभावने पर्वत दृश्यों, शांत मठों और साहसिक खेलों का अनुभव करें',
    'dest.coastalParadise': 'तटीय स्वर्ग',
    'dest.coastalParadise.location': 'दक्षिणी समुद्र तट',
    'dest.coastalParadise.desc': 'क्रिस्टल क्लियर पानी, सुनहरी रेत और जीवंत समुद्री जीवन इंतजार कर रहा है',
    'dest.heritageWonders': 'विरासत के चमत्कार',
    'dest.heritageWonders.location': 'सांस्कृतिक हृदयभूमि',
    'dest.heritageWonders.desc': 'प्राचीन मंदिरों, शाही महलों और समृद्ध सांस्कृतिक परंपराओं का अन्वेषण करें',
    'dest.wildlifeSafari': 'वन्यजीव सफारी',
    'dest.wildlifeSafari.location': 'राष्ट्रीय उद्यान',
    'dest.wildlifeSafari.desc': 'उनके प्राकृतिक आवास में भव्य बाघों, हाथियों और दुर्लभ वन्यजीवों से मिलें',
    'dest.teaGardens': 'चाय बागान',
    'dest.teaGardens.location': 'हिल स्टेशन',
    'dest.teaGardens.desc': 'लुढ़कते चाय बागान, धुंधली पहाड़ियां और औपनिवेशिक आकर्षण',
    'dest.desertAdventure': 'रेगिस्तान साहसिक',
    'dest.desertAdventure.location': 'पश्चिमी रेगिस्तान',
    'dest.desertAdventure.desc': 'ऊंट सफारी, रेत के टीले और तारों भरी रेगिस्तान की रातों का अनुभव करें',
    'dest.goaBeaches': 'गोवा समुद्र तट',
    'dest.goaBeaches.location': 'गोवा',
    'dest.goaBeaches.desc': 'प्रसिद्ध समुद्र तट, नाइटलाइफ, पुर्तगाली वास्तुकला और समुद्री भोजन',
    'dest.varanasiGhats': 'वाराणसी घाट',
    'dest.varanasiGhats.location': 'उत्तर प्रदेश',
    'dest.varanasiGhats.desc': 'प्राचीन घाटों और मंदिरों के साथ भारत की आध्यात्मिक राजधानी',
    'dest.kazirangaSafari': 'काजीरंगा सफारी',
    'dest.kazirangaSafari.location': 'असम',
    'dest.kazirangaSafari.desc': 'एक सींग वाले गैंडे और विविध वन्यजीवों का घर',
    
    // Tags
    'tag.adventure': 'साहसिक',
    'tag.nature': 'प्रकृति',
    'tag.trekking': 'ट्रैकिंग',
    'tag.beach': 'समुद्र तट',
    'tag.relaxation': 'विश्राम',
    'tag.waterSports': 'जल क्रीड़ा',
    'tag.culture': 'संस्कृति',
    'tag.history': 'इतिहास',
    'tag.architecture': 'वास्तुकला',
    'tag.wildlife': 'वन्यजीव',
    'tag.photography': 'फोटोग्राफी',
    'tag.safari': 'सफारी',
    'tag.peaceful': 'शांतिपूर्ण',
    'tag.scenic': 'सुंदर दृश्य',
    'tag.unique': 'अनोखा',
    'tag.nightlife': 'नाइटलाइफ',
    'tag.food': 'भोजन',
    'tag.spiritual': 'आध्यात्मिक',
    'tag.heritage': 'विरासत',
    
    // Experiences Section
    'experiences.badge': 'अनूठे अनुभव',
    'experiences.title': 'अनूठे',
    'experiences.titleHighlight': 'अनुभव',
    'experiences.subtitle': 'हर प्रकार के यात्री के लिए डिज़ाइन की गई इमर्सिव गतिविधियों के साथ दर्शनीय स्थलों से परे जाएं',
    'experiences.bookNow': 'अभी बुक करें',
    'experiences.all': 'सभी',
    'experiences.leisure': 'विश्राम',
    'experiences.noResults': 'इस श्रेणी में कोई अनुभव नहीं मिला।',
    'experiences.selected': 'अनुभव चुना गया!',
    'experiences.addedMessage': 'जोड़ा गया है। अपनी बुकिंग पूरी करने के लिए ट्रिप प्लानर पर जाएं।',
    
    // Experience Names
    'exp.trekkingAdventures': 'ट्रैकिंग साहसिक',
    'exp.trekkingAdventures.desc': 'अनुभवी गाइडों के साथ लुभावने परिदृश्यों के माध्यम से चुनौतीपूर्ण रास्तों पर विजय प्राप्त करें',
    'exp.waterSports': 'जल क्रीड़ा',
    'exp.waterSports.desc': 'प्रमाणित प्रशिक्षकों के साथ प्राचीन जल में सर्फिंग, डाइविंग और कयाकिंग',
    'exp.photographyTours': 'फोटोग्राफी टूर',
    'exp.photographyTours.desc': 'पेशेवर फोटोग्राफरों के साथ अद्भुत परिदृश्यों को कैप्चर करें',
    'exp.culinaryExperiences': 'पाक अनुभव',
    'exp.culinaryExperiences.desc': 'प्रामाणिक स्थानीय व्यंजनों का स्वाद लें और मास्टर शेफ से खाना पकाने के रहस्य सीखें',
    'exp.campingGlamping': 'कैम्पिंग और ग्लैम्पिंग',
    'exp.campingGlamping.desc': 'लक्जरी टेंट या पारंपरिक कैम्पिंग सेटअप में तारों के नीचे सोएं',
    'exp.culturalImmersion': 'सांस्कृतिक विसर्जन',
    'exp.culturalImmersion.desc': 'स्थानीय लोगों के साथ रहें और पारंपरिक शिल्प, नृत्य और रीति-रिवाज सीखें',
    'exp.cyclingTours': 'साइकिलिंग टूर',
    'exp.cyclingTours.desc': 'विशेषज्ञ-निर्देशित साइकिलिंग साहसिक के साथ दो पहियों पर सुंदर मार्गों का अन्वेषण करें',
    'exp.musicDance': 'संगीत और नृत्य',
    'exp.musicDance.desc': 'पारंपरिक संगीत प्रदर्शन का अनुभव करें और लोक नृत्य रूप सीखें',
    
    // Duration & Difficulty
    'duration.3-7days': '3-7 दिन',
    'duration.halfToFull': 'आधे दिन से पूरे दिन',
    'duration.1-5days': '1-5 दिन',
    'duration.2-4hours': '2-4 घंटे',
    'duration.1-3nights': '1-3 रातें',
    'duration.2-7days': '2-7 दिन',
    'duration.2-3hours': '2-3 घंटे',
    'difficulty.moderateToHard': 'मध्यम से कठिन',
    'difficulty.easyToModerate': 'आसान से मध्यम',
    'difficulty.easy': 'आसान',
    'difficulty.moderate': 'मध्यम',
    
    // Features Section
    'features.badge': 'VirtueYatra क्यों चुनें',
    'features.title': 'क्यों चुनें',
    'features.titleHighlight': 'VirtueYatra',
    'features.subtitle': 'अत्याधुनिक तकनीक और व्यक्तिगत सेवा के साथ नए सिरे से यात्रा योजना का अनुभव करें',
    'features.aiAssistant': 'AI यात्रा सहायक',
    'features.aiAssistant.desc': 'अपने सभी यात्रा प्रश्नों के व्यक्तिगत सिफारिशें और तत्काल उत्तर प्राप्त करें',
    'features.smartItinerary': 'स्मार्ट यात्रा योजना',
    'features.smartItinerary.desc': 'AI-अनुकूलित मार्गों और शेड्यूल के साथ सही यात्रा योजनाएं बनाएं',
    'features.immersive': 'इमर्सिव अनुभव',
    'features.immersive.desc': 'आने से पहले AR/VR तकनीक के साथ गंतव्यों का पूर्वावलोकन करें',
    'features.safeSec': 'सुरक्षित और संरक्षित',
    'features.safeSec.desc': 'हमारे सत्यापित भागीदारों और सुरक्षित बुकिंग के साथ आत्मविश्वास से यात्रा करें',
    'features.globalCoverage': 'वैश्विक कवरेज',
    'features.globalCoverage.desc': 'स्थानीय अंतर्दृष्टि के साथ महाद्वीपों भर में गंतव्यों का अन्वेषण करें',
    'features.personalized': 'आपके लिए व्यक्तिगत',
    'features.personalized.desc': 'आपकी प्राथमिकताओं और यात्रा शैली के आधार पर अनुकूलित सिफारिशें',
    
    // Footer
    'footer.tagline': 'असाधारण गंतव्यों की खोज और अविस्मरणीय यादें बनाने के लिए आपका बुद्धिमान यात्रा साथी।',
    'footer.company': 'कंपनी',
    'footer.aboutUs': 'हमारे बारे में',
    'footer.careers': 'करियर',
    'footer.press': 'प्रेस',
    'footer.blog': 'ब्लॉग',
    'footer.support': 'सहायता',
    'footer.helpCenter': 'सहायता केंद्र',
    'footer.safety': 'सुरक्षा',
    'footer.termsOfService': 'सेवा की शर्तें',
    'footer.privacyPolicy': 'गोपनीयता नीति',
    'footer.discover': 'खोजें',
    'footer.destinations': 'गंतव्य',
    'footer.experiences': 'अनुभव',
    'footer.travelGuides': 'यात्रा गाइड',
    'footer.giftCards': 'गिफ्ट कार्ड',
    'footer.rights': 'सर्वाधिकार सुरक्षित।',
    
    // Chatbot
    'chatbot.title': 'VirtueYatra सहायक',
    'chatbot.subtitle': 'हमेशा मदद के लिए यहाँ',
    'chatbot.greeting': 'नमस्ते! 👋 मैं आपका VirtueYatra यात्रा सहायक हूं। आज मैं आपकी सही यात्रा की योजना बनाने में कैसे मदद कर सकता हूं?',
    'chatbot.placeholder': 'मुझसे कुछ भी पूछें...',
    'chatbot.response.hello': 'नमस्ते! मैं आपको अद्भुत गंतव्यों की खोज में मदद करने के लिए उत्साहित हूं। आप किस तरह के अनुभव की तलाश में हैं?',
    'chatbot.response.beach': 'हमारे तटीय स्वर्ग गंतव्य समुद्र तट प्रेमियों के लिए एकदम सही हैं! क्रिस्टल क्लियर पानी और सुनहरी रेत के साथ, आपको विश्राम और रोमांच दोनों मिलेंगे। पैकेज ₹18,499 से शुरू होता है। क्या आप और जानना चाहेंगे?',
    'chatbot.response.mountain': 'हिमालयन ट्रेल्स लुभावने पर्वत दृश्य और साहसिक खेल प्रदान करते हैं! यह ट्रैकिंग और शांत मठों के अनुभव के लिए एकदम सही है। पैकेज ₹25,999 से शुरू होते हैं। बुकिंग में रुचि है?',
    'chatbot.response.budget': 'हमारे पास हर बजट के लिए विकल्प हैं! हमारे पैकेज ₹16,999 से ₹32,999 तक हैं। बजट यात्री हमारे चाय बागान पैकेज को ₹16,999 में पसंद करते हैं, जबकि साहसिक साधक ₹32,999 में वन्यजीव सफारी का आनंद लेते हैं। आपकी बजट सीमा क्या है?',
    'chatbot.response.wildlife': 'हमारे वन्यजीव सफारी पैकेज उनके प्राकृतिक आवास में भव्य बाघों, हाथियों और दुर्लभ वन्यजीवों के साथ अविश्वसनीय मुलाकातें प्रदान करते हैं। फोटोग्राफरों के लिए एकदम सही! ₹32,999 से शुरू। क्या मैं इस साहसिक की योजना बनाने में आपकी मदद करूं?',
    'chatbot.response.book': 'बढ़िया! अपनी यात्रा बुक करने के लिए, मैं नीचे हमारे ट्रिप प्लानर का उपयोग करने की सलाह देता हूं। बस अपना विवरण भरें, और हम आपके लिए एक व्यक्तिगत यात्रा कार्यक्रम बनाएंगे!',
    'chatbot.response.culture': 'हमारा विरासत के चमत्कार टूर आपको प्राचीन मंदिरों, शाही महलों और समृद्ध सांस्कृतिक परंपराओं के माध्यम से ले जाता है। इसकी रेटिंग 4.7 स्टार है और 3,000 से अधिक समीक्षाएं हैं! ₹22,999 से शुरू। क्या आप अधिक विवरण चाहेंगे?',
    'chatbot.response.thank': 'आपका स्वागत है! यदि आपको अपनी यात्रा की योजना बनाने में किसी और मदद की आवश्यकता है, तो मैं हमेशा यहाँ हूं। शुभ यात्रा! 🌍✈️',
    'chatbot.response.default': 'यह एक बढ़िया सवाल है! मैं गंतव्यों, मूल्य निर्धारण, बुकिंग जानकारी और यात्रा सिफारिशों में आपकी मदद कर सकता हूं। समुद्र तटों, पहाड़ों, वन्यजीवों, सांस्कृतिक अनुभवों या किसी भी विशिष्ट यात्रा आवश्यकताओं के बारे में बेझिझक पूछें!',
    
    // Toast messages
    'toast.missingInfo': 'जानकारी अधूरी है',
    'toast.fillDestinationDates': 'कृपया गंतव्य और तिथियां भरें।',
    'toast.errorSavingTrip': 'यात्रा सहेजने में त्रुटि',
    'toast.tripCreated': 'यात्रा योजना बनाई गई!',
    'toast.tripSaved': '{destination} की आपकी यात्रा सहेज ली गई है!',
    'toast.tripReadySignIn': '{destination} के लिए आपका यात्रा कार्यक्रम तैयार है! अपनी यात्राएं सहेजने के लिए साइन इन करें।',
    'toast.tripDeleted': 'यात्रा हटाई गई',
    'toast.tripDeletedDesc': 'आपकी यात्रा इतिहास से हटा दी गई है।',
    
    // Virtual World
    'virtualWorld.button': 'वर्चुअल वर्ल्ड देखें',
    'virtualWorld.title': '360° वर्चुअल टूर',
    'virtualWorld.clickToExplore': '360° अनुभव शुरू करने के लिए क्लिक करें',
    'virtualWorld.selectDestination': 'गंतव्य चुनें',
    'virtualWorld.tip': '💡 सुझाव: 360° में देखने के लिए खींचें। ज़ूम करने के लिए माउस व्हील का उपयोग करें।',
  },
  te: {
    // Header
    'nav.destinations': 'గమ్యస్థానాలు',
    'nav.experiences': 'అనుభవాలు',
    'nav.plan': 'ప్రయాణ ప్రణాళిక',
    'nav.signIn': 'సైన్ ఇన్',
    'nav.signOut': 'సైన్ అవుట్',
    
    // Hero
    'hero.badge': '1000+ గమ్యస్థానాలు అన్వేషించండి',
    'hero.title1': 'మీ తదుపరి కనుగొనండి',
    'hero.title2': 'సాహసం వేచి ఉంది',
    'hero.subtitle': 'AI-ఆధారిత ప్రయాణ ప్రణాళిక, వ్యక్తిగతీకరించిన యాత్రా పథకాలు మరియు ఇమర్సివ్ అనుభవాలతో అసాధారణ ప్రయాణాలకు బయలుదేరండి',
    'hero.startPlanning': 'ప్రణాళిక ప్రారంభించండి',
    'hero.exploreDestinations': 'గమ్యస్థానాలు అన్వేషించండి',
    'hero.destinations': 'గమ్యస్థానాలు',
    'hero.support': 'సపోర్ట్',
    
    // Trip Planner
    'planner.badge': 'AI-ఆధారిత ప్రణాళిక',
    'planner.title': 'మీ ప్రణాళిక',
    'planner.titleHighlight': 'పర్ఫెక్ట్ ట్రిప్',
    'planner.subtitle': 'మీ ప్రాధాన్యతల ఆధారంగా వ్యక్తిగతీకరించిన యాత్రా పథకాన్ని మా AI సహాయకుడు సృష్టించనివ్వండి',
    'planner.viewHistory': 'చూడండి',
    'planner.hideHistory': 'దాచు',
    'planner.bookingHistory': 'బుకింగ్ చరిత్ర',
    'planner.yourBookingHistory': 'మీ బుకింగ్ చరిత్ర',
    'planner.destination': 'గమ్యస్థానం',
    'planner.whereTo': 'ఎక్కడికి?',
    'planner.startDate': 'ప్రారంభ తేదీ',
    'planner.endDate': 'ముగింపు తేదీ',
    'planner.travelers': 'ప్రయాణికుల సంఖ్య',
    'planner.traveler': 'ప్రయాణికుడు',
    'planner.travelersPlural': 'ప్రయాణికులు',
    'planner.budget': 'బడ్జెట్ పరిధి',
    'planner.selectBudget': 'బడ్జెట్ ఎంచుకోండి',
    'planner.budgetLow': 'బడ్జెట్ (₹10k - ₹25k)',
    'planner.budgetModerate': 'మధ్యస్థ (₹25k - ₹50k)',
    'planner.budgetLuxury': 'లగ్జరీ (₹50k - ₹1L)',
    'planner.budgetPremium': 'ప్రీమియం (₹1L+)',
    'planner.interests': 'మీ ఆసక్తులు',
    'planner.selectInterests': 'మీకు ఇష్టమైన కార్యకలాపాలను ఎంచుకోండి',
    'planner.specialRequests': 'ప్రత్యేక అభ్యర్థనలు',
    'planner.specialRequestsPlaceholder': 'ఏదైనా నిర్దిష్ట అవసరాలు, ఆహార పరిమితులు, యాక్సెసిబిలిటీ అవసరాలు...',
    'planner.createItinerary': 'నా యాత్రా పథకం సృష్టించండి',
    'planner.creating': 'సృష్టిస్తోంది...',
    'planner.tripPlanned': 'మీ ట్రిప్ ప్రణాళిక చేయబడింది!',
    'planner.savedToHistory': 'మీ ట్రిప్ మీ బుకింగ్ చరిత్రలో సేవ్ చేయబడింది',
    'planner.signInToSave': 'మీ ట్రిప్‌లను సేవ్ చేయడానికి సైన్ ఇన్ చేయండి',
    'planner.travelDates': 'ప్రయాణ తేదీలు',
    'planner.to': 'నుండి',
    'planner.person': 'వ్యక్తి',
    'planner.people': 'వ్యక్తులు',
    'planner.selectedInterests': 'ఎంచుకున్న ఆసక్తులు',
    'planner.planAnotherTrip': 'మరో ట్రిప్ ప్లాన్ చేయండి',
    'planner.getDetailedItinerary': 'వివరణాత్మక యాత్రా పథకం చూడండి',
    'planner.hideItinerary': 'యాత్రా పథకం దాచు',
    
    // Itinerary
    'itinerary.title': 'మీ వివరణాత్మక యాత్రా పథకం',
    'itinerary.day': 'రోజు',
    'itinerary.morning': 'ఉదయం',
    'itinerary.afternoon': 'మధ్యాహ్నం',
    'itinerary.evening': 'సాయంత్రం',
    'itinerary.tips': 'ప్రయాణ చిట్కాలు',
    'itinerary.tip1': 'రోజు పర్యటనల కోసం తేలికపాటి కాటన్ బట్టలు తీసుకెళ్ళండి',
    'itinerary.tip2': 'చిన్న కొనుగోళ్లకు స్థానిక కరెన్సీ ఉంచుకోండి',
    'itinerary.tip3': 'హైడ్రేటెడ్‌గా ఉండండి మరియు నీటి బాటిల్ తీసుకెళ్ళండి',
    'itinerary.tip4': 'స్థానిక ఆచారాలు మరియు సంప్రదాయాలను గౌరవించండి',
    
    // Interests
    'interest.adventure': 'సాహసం',
    'interest.beach': 'బీచ్',
    'interest.culture': 'సంస్కృతి',
    'interest.wildlife': 'వన్యప్రాణులు',
    'interest.photography': 'ఫోటోగ్రఫీ',
    'interest.food': 'ఆహారం',
    'interest.hiking': 'హైకింగ్',
    'interest.relaxation': 'విశ్రాంతి',
    'interest.shopping': 'షాపింగ్',
    'interest.history': 'చరిత్ర',
    
    // Destinations Section
    'destinations.badge': 'ప్రసిద్ధ గమ్యస్థానాలు',
    'destinations.title': 'ప్రసిద్ధ',
    'destinations.titleHighlight': 'గమ్యస్థానాలు',
    'destinations.subtitle': 'మరపురాని అనుభవాలను వాగ్దానం చేసే చేతితో ఎంచుకున్న గమ్యస్థానాలు',
    'destinations.bookNow': 'ఇప్పుడే బుక్ చేయండి',
    'destinations.all': 'అన్నీ',
    'destinations.trending': 'ట్రెండింగ్',
    'destinations.startingFrom': 'మొదలు',
    'destinations.reviews': 'సమీక్షలు',
    'destinations.noResults': 'ఈ వర్గంలో గమ్యస్థానాలు కనుగొనబడలేదు.',
    
    // Destination Names
    'dest.himalayanTrails': 'హిమాలయన్ ట్రయిల్స్',
    'dest.himalayanTrails.location': 'ఉత్తర పర్వతాలు',
    'dest.himalayanTrails.desc': 'అద్భుతమైన పర్వత దృశ్యాలు, ప్రశాంత మఠాలు మరియు సాహస క్రీడలను అనుభవించండి',
    'dest.coastalParadise': 'తీర స్వర్గం',
    'dest.coastalParadise.location': 'దక్షిణ బీచ్‌లు',
    'dest.coastalParadise.desc': 'క్రిస్టల్ క్లియర్ నీళ్ళు, బంగారు ఇసుక మరియు శక్తివంతమైన సముద్ర జీవితం వేచి ఉన్నాయి',
    'dest.heritageWonders': 'వారసత్వ అద్భుతాలు',
    'dest.heritageWonders.location': 'సాంస్కృతిక హృదయభూమి',
    'dest.heritageWonders.desc': 'ప్రాచీన దేవాలయాలు, రాజభవనాలు మరియు సమృద్ధ సాంస్కృతిక సంప్రదాయాలను అన్వేషించండి',
    'dest.wildlifeSafari': 'వన్యప్రాణి సఫారీ',
    'dest.wildlifeSafari.location': 'జాతీయ ఉద్యానవనాలు',
    'dest.wildlifeSafari.desc': 'వారి సహజ ఆవాసంలో గంభీరమైన పులులు, ఏనుగులు మరియు అరుదైన వన్యప్రాణులను కలవండి',
    'dest.teaGardens': 'టీ తోటలు',
    'dest.teaGardens.location': 'హిల్ స్టేషన్లు',
    'dest.teaGardens.desc': 'వంగిన టీ తోటలు, మంచు కొండలు మరియు వలసరాజ్యపు ఆకర్షణ',
    'dest.desertAdventure': 'ఎడారి సాహసం',
    'dest.desertAdventure.location': 'పశ్చిమ ఎడారులు',
    'dest.desertAdventure.desc': 'ఒంటె సఫారీలు, ఇసుక దిబ్బలు మరియు నక్షత్రాల ఎడారి రాత్రులను అనుభవించండి',
    'dest.goaBeaches': 'గోవా బీచ్‌లు',
    'dest.goaBeaches.location': 'గోవా',
    'dest.goaBeaches.desc': 'ప్రసిద్ధ బీచ్‌లు, నైట్‌లైఫ్, పోర్చుగీస్ వాస్తుశిల్పం మరియు సీఫుడ్',
    'dest.varanasiGhats': 'వారణాసి ఘాట్‌లు',
    'dest.varanasiGhats.location': 'ఉత్తర ప్రదేశ్',
    'dest.varanasiGhats.desc': 'ప్రాచీన ఘాట్‌లు మరియు దేవాలయాలతో భారతదేశ ఆధ్యాత్మిక రాజధాని',
    'dest.kazirangaSafari': 'కాజీరంగా సఫారీ',
    'dest.kazirangaSafari.location': 'అసోం',
    'dest.kazirangaSafari.desc': 'ఒంటి కొమ్ము ఖడ్గమృగం మరియు వైవిధ్యమైన వన్యప్రాణులకు నిలయం',
    
    // Tags
    'tag.adventure': 'సాహసం',
    'tag.nature': 'ప్రకృతి',
    'tag.trekking': 'ట్రెక్కింగ్',
    'tag.beach': 'బీచ్',
    'tag.relaxation': 'విశ్రాంతి',
    'tag.waterSports': 'వాటర్ స్పోర్ట్స్',
    'tag.culture': 'సంస్కృతి',
    'tag.history': 'చరిత్ర',
    'tag.architecture': 'వాస్తుశిల్పం',
    'tag.wildlife': 'వన్యప్రాణులు',
    'tag.photography': 'ఫోటోగ్రఫీ',
    'tag.safari': 'సఫారీ',
    'tag.peaceful': 'ప్రశాంతమైన',
    'tag.scenic': 'అందమైన దృశ్యం',
    'tag.unique': 'ప్రత్యేకమైన',
    'tag.nightlife': 'నైట్‌లైఫ్',
    'tag.food': 'ఆహారం',
    'tag.spiritual': 'ఆధ్యాత్మిక',
    'tag.heritage': 'వారసత్వం',
    
    // Experiences Section
    'experiences.badge': 'ప్రత్యేక అనుభవాలు',
    'experiences.title': 'ప్రత్యేక',
    'experiences.titleHighlight': 'అనుభవాలు',
    'experiences.subtitle': 'ప్రతి రకమైన ప్రయాణికుడికి రూపొందించిన ఇమర్సివ్ కార్యకలాపాలతో దర్శనీయ స్థలాలకు మించి వెళ్ళండి',
    'experiences.bookNow': 'ఇప్పుడే బుక్ చేయండి',
    'experiences.all': 'అన్నీ',
    'experiences.leisure': 'విశ్రాంతి',
    'experiences.noResults': 'ఈ వర్గంలో అనుభవాలు కనుగొనబడలేదు.',
    'experiences.selected': 'అనుభవం ఎంచుకోబడింది!',
    'experiences.addedMessage': 'జోడించబడింది. మీ బుకింగ్ పూర్తి చేయడానికి ట్రిప్ ప్లానర్‌కు వెళ్ళండి.',
    
    // Experience Names
    'exp.trekkingAdventures': 'ట్రెక్కింగ్ సాహసాలు',
    'exp.trekkingAdventures.desc': 'అనుభవజ్ఞులైన గైడ్‌లతో అద్భుతమైన ప్రకృతి దృశ్యాల గుండా సవాలు మార్గాలను జయించండి',
    'exp.waterSports': 'వాటర్ స్పోర్ట్స్',
    'exp.waterSports.desc': 'ధృవీకరించబడిన శిక్షకులతో ప్రిస్టీన్ నీటిలో సర్ఫింగ్, డైవింగ్ మరియు కయాకింగ్',
    'exp.photographyTours': 'ఫోటోగ్రఫీ టూర్లు',
    'exp.photographyTours.desc': 'ప్రొఫెషనల్ ఫోటోగ్రాఫర్లతో అద్భుతమైన ప్రకృతి దృశ్యాలను క్యాప్చర్ చేయండి',
    'exp.culinaryExperiences': 'వంటకాల అనుభవాలు',
    'exp.culinaryExperiences.desc': 'అసలైన స్థానిక వంటకాలను రుచి చూడండి మరియు మాస్టర్ షెఫ్‌ల నుండి వంట రహస్యాలు నేర్చుకోండి',
    'exp.campingGlamping': 'క్యాంపింగ్ & గ్లాంపింగ్',
    'exp.campingGlamping.desc': 'లగ్జరీ టెంట్లు లేదా సాంప్రదాయ క్యాంపింగ్ సెటప్‌లలో నక్షత్రాల కింద నిద్రపోండి',
    'exp.culturalImmersion': 'సాంస్కృతిక నిమజ్జనం',
    'exp.culturalImmersion.desc': 'స్థానికులతో నివసించండి మరియు సాంప్రదాయ హస్తకళలు, నృత్యం మరియు ఆచారాలు నేర్చుకోండి',
    'exp.cyclingTours': 'సైక్లింగ్ టూర్లు',
    'exp.cyclingTours.desc': 'నిపుణ-మార్గదర్శిత సైక్లింగ్ సాహసాలతో రెండు చక్రాలపై అందమైన మార్గాలను అన్వేషించండి',
    'exp.musicDance': 'సంగీతం & నృత్యం',
    'exp.musicDance.desc': 'సాంప్రదాయ సంగీత ప్రదర్శనలను అనుభవించండి మరియు జానపద నృత్య రూపాలు నేర్చుకోండి',
    
    // Duration & Difficulty
    'duration.3-7days': '3-7 రోజులు',
    'duration.halfToFull': 'సగం రోజు నుండి పూర్తి రోజు',
    'duration.1-5days': '1-5 రోజులు',
    'duration.2-4hours': '2-4 గంటలు',
    'duration.1-3nights': '1-3 రాత్రులు',
    'duration.2-7days': '2-7 రోజులు',
    'duration.2-3hours': '2-3 గంటలు',
    'difficulty.moderateToHard': 'మధ్యస్థ నుండి కఠినం',
    'difficulty.easyToModerate': 'సులభం నుండి మధ్యస్థం',
    'difficulty.easy': 'సులభం',
    'difficulty.moderate': 'మధ్యస్థం',
    
    // Features Section
    'features.badge': 'VirtueYatra ఎందుకు ఎంచుకోవాలి',
    'features.title': 'ఎందుకు ఎంచుకోవాలి',
    'features.titleHighlight': 'VirtueYatra',
    'features.subtitle': 'అత్యాధునిక సాంకేతికత మరియు వ్యక్తిగతీకరించిన సేవతో పునర్నిర్మించిన ప్రయాణ ప్రణాళికను అనుభవించండి',
    'features.aiAssistant': 'AI ప్రయాణ సహాయకుడు',
    'features.aiAssistant.desc': 'మీ అన్ని ప్రయాణ ప్రశ్నలకు వ్యక్తిగతీకరించిన సిఫార్సులు మరియు తక్షణ సమాధానాలు పొందండి',
    'features.smartItinerary': 'స్మార్ట్ యాత్రా ప్రణాళిక',
    'features.smartItinerary.desc': 'AI-ఆప్టిమైజ్ చేసిన మార్గాలు మరియు షెడ్యూల్‌లతో పర్ఫెక్ట్ ప్రయాణ ప్రణాళికలను సృష్టించండి',
    'features.immersive': 'ఇమర్సివ్ అనుభవాలు',
    'features.immersive.desc': 'మీరు సందర్శించడానికి ముందు AR/VR సాంకేతికతతో గమ్యస్థానాలను ప్రివ్యూ చేయండి',
    'features.safeSec': 'సురక్షితమైన & సెక్యూర్',
    'features.safeSec.desc': 'మా ధృవీకరించబడిన భాగస్వాములు మరియు సురక్షిత బుకింగ్‌తో నమ్మకంగా ప్రయాణించండి',
    'features.globalCoverage': 'గ్లోబల్ కవరేజ్',
    'features.globalCoverage.desc': 'స్థానిక అంతర్దృష్టులతో ఖండాల అంతటా గమ్యస్థానాలను అన్వేషించండి',
    'features.personalized': 'మీ కోసం వ్యక్తిగతీకరించబడింది',
    'features.personalized.desc': 'మీ ప్రాధాన్యతలు మరియు ప్రయాణ శైలి ఆధారంగా అనుకూలీకరించిన సిఫార్సులు',
    
    // Footer
    'footer.tagline': 'అసాధారణ గమ్యస్థానాలను కనుగొనడానికి మరియు మరపురాని జ్ఞాపకాలను సృష్టించడానికి మీ తెలివైన ప్రయాణ సహచరుడు.',
    'footer.company': 'కంపెనీ',
    'footer.aboutUs': 'మా గురించి',
    'footer.careers': 'కెరీర్లు',
    'footer.press': 'ప్రెస్',
    'footer.blog': 'బ్లాగ్',
    'footer.support': 'సపోర్ట్',
    'footer.helpCenter': 'సహాయ కేంద్రం',
    'footer.safety': 'భద్రత',
    'footer.termsOfService': 'సేవా నిబంధనలు',
    'footer.privacyPolicy': 'గోప్యతా విధానం',
    'footer.discover': 'కనుగొనండి',
    'footer.destinations': 'గమ్యస్థానాలు',
    'footer.experiences': 'అనుభవాలు',
    'footer.travelGuides': 'ప్రయాణ గైడ్‌లు',
    'footer.giftCards': 'గిఫ్ట్ కార్డ్‌లు',
    'footer.rights': 'అన్ని హక్కులు రిజర్వ్ చేయబడ్డాయి.',
    
    // Chatbot
    'chatbot.title': 'VirtueYatra సహాయకుడు',
    'chatbot.subtitle': 'సహాయం చేయడానికి ఎల్లప్పుడూ ఇక్కడ',
    'chatbot.greeting': 'నమస్కారం! 👋 నేను మీ VirtueYatra ప్రయాణ సహాయకుడిని. ఈ రోజు మీ పర్ఫెక్ట్ ట్రిప్ ప్లాన్ చేయడంలో నేను మీకు ఎలా సహాయం చేయగలను?',
    'chatbot.placeholder': 'నన్ను ఏదైనా అడగండి...',
    'chatbot.response.hello': 'నమస్కారం! అద్భుతమైన గమ్యస్థానాలను కనుగొనడంలో మీకు సహాయం చేయడానికి నేను సంతోషిస్తున్నాను. మీరు ఏ రకమైన అనుభవం కోసం చూస్తున్నారు?',
    'chatbot.response.beach': 'మా తీర స్వర్గ గమ్యస్థానాలు బీచ్ ప్రేమికులకు అద్భుతం! క్రిస్టల్ క్లియర్ నీళ్ళు మరియు బంగారు ఇసుకతో, మీరు విశ్రాంతి మరియు సాహసం రెండూ కనుగొంటారు. ప్యాకేజీ ₹18,499 నుండి ప్రారంభమవుతుంది. మరింత తెలుసుకోవాలనుకుంటున్నారా?',
    'chatbot.response.mountain': 'హిమాలయన్ ట్రయిల్స్ అద్భుతమైన పర్వత దృశ్యాలు మరియు సాహస క్రీడలను అందిస్తాయి! ట్రెక్కింగ్ మరియు ప్రశాంత మఠాలను అనుభవించడానికి ఇది అద్భుతం. ప్యాకేజీలు ₹25,999 నుండి ప్రారంభమవుతాయి. బుక్ చేయడానికి ఆసక్తి ఉందా?',
    'chatbot.response.budget': 'మాకు ప్రతి బడ్జెట్‌కు ఎంపికలు ఉన్నాయి! మా ప్యాకేజీలు ₹16,999 నుండి ₹32,999 వరకు ఉన్నాయి. బడ్జెట్ ప్రయాణికులు ₹16,999లో మా టీ తోటల ప్యాకేజీని ఇష్టపడతారు, సాహస సాధకులు ₹32,999లో వన్యప్రాణి సఫారీని ఆనందిస్తారు. మీ బడ్జెట్ పరిధి ఏమిటి?',
    'chatbot.response.wildlife': 'మా వన్యప్రాణి సఫారీ ప్యాకేజీలు వారి సహజ ఆవాసంలో గంభీరమైన పులులు, ఏనుగులు మరియు అరుదైన వన్యప్రాణులతో అద్భుతమైన ఎన్‌కౌంటర్లను అందిస్తాయి. ఫోటోగ్రాఫర్లకు అద్భుతం! ₹32,999 నుండి ప్రారంభమవుతుంది. ఈ సాహసాన్ని ప్లాన్ చేయడంలో నేను మీకు సహాయం చేయనా?',
    'chatbot.response.book': 'గొప్పది! మీ ట్రిప్ బుక్ చేయడానికి, కింద మా ట్రిప్ ప్లానర్ ఉపయోగించమని నేను సిఫార్సు చేస్తాను. మీ వివరాలు నింపండి, మేము మీ కోసం వ్యక్తిగతీకరించిన యాత్రా పథకాన్ని సృష్టిస్తాము!',
    'chatbot.response.culture': 'మా వారసత్వ అద్భుతాల టూర్ మిమ్మల్ని ప్రాచీన దేవాలయాలు, రాజభవనాలు మరియు సమృద్ధ సాంస్కృతిక సంప్రదాయాల ద్వారా తీసుకెళ్తుంది. ఇది 4.7 స్టార్లు మరియు 3,000 కంటే ఎక్కువ సమీక్షలు పొందింది! ₹22,999 నుండి ప్రారంభమవుతుంది. మరిన్ని వివరాలు కావాలా?',
    'chatbot.response.thank': 'మీకు స్వాగతం! మీ ట్రిప్ ప్లాన్ చేయడంలో మీకు మరింత సహాయం అవసరమైతే, నేను ఎల్లప్పుడూ ఇక్కడ ఉన్నాను. శుభ ప్రయాణం! 🌍✈️',
    'chatbot.response.default': 'అది గొప్ప ప్రశ్న! గమ్యస్థానాలు, ధరలు, బుకింగ్ సమాచారం మరియు ప్రయాణ సిఫార్సులతో నేను మీకు సహాయం చేయగలను. బీచ్‌లు, పర్వతాలు, వన్యప్రాణులు, సాంస్కృతిక అనుభవాలు లేదా ఏదైనా నిర్దిష్ట ప్రయాణ అవసరాల గురించి అడగడానికి సంకోచించకండి!',
    
    // Toast messages
    'toast.missingInfo': 'సమాచారం లేదు',
    'toast.fillDestinationDates': 'దయచేసి గమ్యస్థానం మరియు తేదీలను పూరించండి.',
    'toast.errorSavingTrip': 'ట్రిప్ సేవ్ చేయడంలో లోపం',
    'toast.tripCreated': 'ట్రిప్ ప్లాన్ సృష్టించబడింది!',
    'toast.tripSaved': '{destination}కి మీ ట్రిప్ సేవ్ చేయబడింది!',
    'toast.tripReadySignIn': '{destination} కోసం మీ యాత్రా పథకం సిద్ధంగా ఉంది! మీ ట్రిప్‌లను సేవ్ చేయడానికి సైన్ ఇన్ చేయండి.',
    'toast.tripDeleted': 'ట్రిప్ తొలగించబడింది',
    'toast.tripDeletedDesc': 'మీ ట్రిప్ చరిత్ర నుండి తొలగించబడింది.',
    
    // Virtual World
    'virtualWorld.button': 'వర్చువల్ వరల్డ్ చూడండి',
    'virtualWorld.title': '360° వర్చువల్ టూర్లు',
    'virtualWorld.clickToExplore': '360° అనుభవాన్ని ప్రారంభించడానికి క్లిక్ చేయండి',
    'virtualWorld.selectDestination': 'గమ్యస్థానం ఎంచుకోండి',
    'virtualWorld.tip': '💡 చిట్కా: 360°లో చూడటానికి డ్రాగ్ చేయండి. జూమ్ చేయడానికి మౌస్ వీల్ ఉపయోగించండి.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('virtueYatra-language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('virtueYatra-language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
